### ISSUE TITLE
Add a count for every type of NFT minted?

### ISSUE THREAD

**Issue by Edyxia** [czmathew/TBillStakingDashboard#25]
For the NFT counting, I think each type of NFT has its own smart contract and or # edition, if we can figure out which are which, it'll be easier

We found this : https://ipfs.io/ipfs/QmYoxxXQ6hHMuMLfinrwvnZBszASGfPXcvg5JbyRgNmnTa/t16277

We can play with the last part after the t and create a DB for it.

![IMG_9179](https://user-images.githubusercontent.com/79707346/159753995-581b4690-7974-4a56-91fd-e4496e43d104.PNG)

![IMG_9178](https://user-images.githubusercontent.com/79707346/159753918-bedf1e6e-76f2-4609-96b1-38ea98e6b231.PNG)

**Comment by czmathew** [comment]
job has been created to fetch info about each NFT, but the problem is that all the NFT has been minted. The mint on opentheta.io just distributed the NFT to wallets. All those NFTs that were available for "mint" on opentheta.io have already been "pre-minted". This makes it impossible to check for "minted" NFTs on opentheta. We cannot get the number of "minted" NFTs this way... need to figure out some other way, but at least we'll have info about all the NFTs (from this contract) and can display NFT info in My Wallet page
